
name: 'Deploy to AWS CloudFormation'

on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code from master branch
        uses: actions/checkout@v2

      # Configure AWS Credential
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        env:
          aws-access-key-id: ASIA2YUNDFXWGILTKAQI
          aws-secret-access-key: cxiMmPJ4CNEJI26G9NOQ5cwYUgy+MADsm8BCozvz
          aws-region: 'us-east-1'
          Aaws-session-token: FwoGZXIvYXdzEBwaDKk/NznpF5uX/XhqPCLFAc09bawAuPd/+kDKqHweTb+Wo/bf7Yhhn9MS1nLPJF9gWQyQBdPl6EI3Q0nzb89PaPLcL4Zzy5xv0LVOMxVJ6cHixQuewtq49wM+lhFODUlBhg04JpeJXlK8b36kZRn3n6zvgF1TkMYVDzXcN5PfllcWArfcDR8HC2QcB/OwtypxLglF+QT4jAO+svXL7sBgwkQ6lYhuoyu1SrJ3oDezaLb9s/DvHX5NCdEwBZQuzMSnJzKn19cinlFCqLo0TpECztK9Z6ZCKNPevaAGMi3QK0ashS/GsEkaFuy8B1A9lhATTW39tJU9zB0+eL009/PC5Galj+1JsqVPN20=

      # Deploy to AWS CloudFormation
      - name: Deploy to AWS CloudFormation
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: test-stack
          template: Final-CFT.yml
          no-fail-on-empty-changeset: "1"
